import React from 'react';

const youlie = [
    'YOU LIE in the great listening,',
    'ambushed, snowed in.',
    '',
    'Go to the Spree, go to the Havel,',
    'go to the butcher hooks,',
    'to the red apple stakes',
    'from Sweden—',
    '',
    'Here comes the table with the presents,',
    'he turns around an Eden—',
    '',
    'The man became a sieve, the woman',
    'had to swim, the sow,',
    'for herself, for none, for everyone—',
    '',
    'The Landwehr canal will not roar.',
    'Nothing',
    '\tstalls',
];

const twilight = [
    'Let us praise the twilight of freedom, brothers,',
    'the great year of twilight!',
    'A thick forest of nets has been let down',
    'into the seething waters of night.',
    'O sun, judge, people, desolate',
    'are the years into which you are rising!',
    '',
    'Let us praise the momentous burden',
    'that the people’s leader assumes, in tears.',
    'Let us praise the twilight burden of power,',
    'its weight too great to be borne.',
    'Time, whoever has a heart',
    'will hear your ship going down.',
    '',
    'We have roped swallows together',
    'into legions.',
    'Now we can’t see the sun.',
    'Everywhere nature twitters as it moves.',
    'In the deepening twilight the earth swims into the nets',
    'and the sun can’t be seen.',
    '',
    'But what can we lose if we try one',
    'groaning, wide, ungainly sweep of the rudder?',
    'The earth swims. Courage,',
    'brothers, as the cleft sea falls back from our plow.',
    'Even as we freeze in Lethe we’ll remember',
    'the ten heavens the earth cost us.',
];

const inone = [
    'February 13. In heart’s mouth',
    'awakened shibboleth. With you,',
    'Peuple',
    'de Paris. No pasarán.',
    '',
    'Lambs to the left: he, Abadias,',
    'the old man from Huesca, came with his dogs',
    'across the field, in exile',
    'stood white cloud',
    'of human nobility, spoke',
    'the word into our hand, the one we needed, it was',
    'shepherd’s Spanish, in it,',
    '',
    'in the icelight of the cruiser “Aurora”:',
    'the brotherhand, waving the',
    'blinders pulled off the wordwide eyes—Petropolis, the',
    'unforgotten wander-city lay',
    'tuscanly on your heart too.',
    '',
    'Peace to the huts!',
];

const horseshoe = [
    'We look at a forest and say:',
    'Here is a forest for ships and masts,',
    'Red pines,',
    'Free to their tops of their shaggy burden,',
    'To creak in the storm',
    'In the furious forestless air;',
    'The plumbline fastened to the dancing deck',
    'Will hold out under the wind’s salt heel.',
    'And the sea-wanderer,',
    'In his unbridled thirst for space,',
    'Dragging through damp ruts a geometer’s needle,',
    'Collates the rough surface of the seas',
    'With the attraction of the earth’s lap.',
    '',
    'But breathing the smell',
    'Of resinous tears oozing through planks,',
    'Admiring the boards of bulkheads riveted',
    'Not by the peaceful Bethlehem carpenter but by that other –',
    'Father of journeys, friend of seafarers –',
    'We say:',
    'These too stood on the earth,',
    'Awkward as a donkey’s backbone,',
    'Their crests forgetful of their roots,',
    'On a celebrated mountain ridge;',
    'And howled under the sweet cloud-burst,',
    'Fruitlessly offering the sky their precious freight',
    'For a pinch of salt.',
    '',
    'Where shall we begin?',
    'Everything pitches and splits,',
    'The air quivers with comparisons,',
    'No one word is better than another,',
    'The earth hums with metaphors.',
    'And light two-wheeled chariots,',
    'Harnessed brightly to flocks of strenuous birds,',
    'Explode,',
    'Vying with the snorting favourites of the race-track.',
    '',
    'Three times blest he who puts a name into song;',
    'A song adorned with a name',
    'Survives longer among the others,',
    'Marked by a fillet',
    'That frees it from forgetfulness and stupefying smells,',
    '',
    'Whether proximity of man or the smell of a beast’s pelt',
    'Or simply a whiff of thyme rubbed between the palms.',
    '',
    'The air dark like water, everything alive swims like fish,',
    'Fins pushing aside the sphere',
    'That’s compact, resilient, hardly heated –',
    'The crystal in which wheels move and horses shy,',
    'The moist black-earth every night flung open anew',
    'By pitchforks, tridents, hoes and ploughs.',
    'The air is mixed as densely as the earth –',
    'You can’t get out, to get inside is arduous.',
    '',
    'Rustling runs through the trees like a green ball-game;',
    'Children play knucklebones with the vertebrae of dead animals.',
    'The fragile calculation of the years of our era ends.',
    'Let us be grateful for what we had:',
    'I too made mistakes, lost my way, lost count.',
    'The era rang like a golden sphere,',
    'Cast, hollow, supported by no one.',
    'Touched, it answered yes and no,',
    'As a child will say:',
    'I’ll give you an apple, or: I won’t give you one;',
    'Its face an exact copy of the voice that pronounces these words.',
    '',
    'The sound is still ringing although its source has ceased.',
    'The horse foams in the dust.',
    'But the acute curve of his neck',
    'Preserves the memory of the race with outstretched legs',
    'When there were not four',
    'But as many as the stones on the road,',
    'Renewed in four shifts',
    'As blazing hooves pushed off from the ground.',
    '',
    'So,',
    'Whoever finds a horseshoe',
    'Blows away the dust,',
    'Rubs it with wool till it shines,',
    'Then',
    'Hangs it over the threshold',
    'To rest,',
    'So that it will no longer have to strike sparks from flint.',
    '',
    'Human lips',
    ' which have nothing more to say',
    'Preserve the form of the last word said.',
    'And the arm retains the sense of weight',
    'Though the jug',
    ' splashes half-empty',
    ' on the way home.',
    '',
    'What I am saying at this moment is not being said by me',
    'But is dug from the ground like grains of petrified wheat.',
    'Some',
    ' on their coins depict a lion,',
    'Others',
    ' a head;',
    'Various tablets of brass, of gold and bronze',
    'Lie with equal honour in the earth.',
    'The century, trying to bite through them, left its teeth-marks there.',
    'Time pares me down like a coin,',
    'And there is no longer enough of me for myself.',
];
export { youlie, twilight, inone, horseshoe };
